# Dockerfile for the orchestrator
FROM golang:1.19-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY internal/ internal/

RUN go build -o ./out/orchestrator ./cmd/orchestrator

EXPOSE 8081

CMD [ "./out/orchestrator" ]
